#!/usr/bin/env python3
"""Merlin setup helper. Run through setup.sh, which checks python3 first.

Every change outside the Merlin data folder is recorded in ~/.merlin/setup-record.json,
so `--remove` reverses exactly what setup added and nothing else. Honours a HOME
override (every home path comes from os.path.expanduser). Never reads a plugin variable:
the plugin folder is found from this file's own location.

Modes (one per run):
  --check                 report only; writes nothing anywhere
  --skeleton-only         copy the starter files into the data folder (never overwrites),
                          then report; no questions, no settings changes
  --skeleton              same copy, used by the interactive setup
  --grant [--yes]         add the data folder to permissions.additionalDirectories in
                          ~/.claude/settings.json (preview without --yes; backup first)
  --codex-status          report Codex: installed, Merlin present, start-up hook trusted
  --codex-block [--yes]   add the managed Merlin block to ~/.codex/AGENTS.md (preview
                          without --yes)
  --key-store NAME        store a key in the macOS Keychain, service "Merlin"; the value
                          is read from stdin and never printed
  --key-check NAME        print "ok" or "missing", never the value
  --explain-memory        print the plain-words note about Claude Code's own memory
  --remove [--yes] [--keys A,B]
                          reverse what setup and the start-up hook wrote outside the data
                          folder (preview without --yes); never touches the data folder
Common: --data DIR (default: the folder named in ~/.merlin/instance.json)
"""

import argparse
import datetime
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys

BUILD_MARKER = '<!-- Generated by the plugin build.'
KEYCHAIN_SERVICE = 'Merlin'
CODEX_BEGIN = '<!-- BEGIN MERLIN (managed by merlin:setup; remove with merlin:setup --remove) -->'
CODEX_END = '<!-- END MERLIN -->'
CODEX_TRUST_RE = re.compile(r'^\[hooks\.state\."[^"]*/merlin/[^"]*hooks\.json:session_start:', re.M)

MEMORY_NOTE = """Claude's own memory, in plain words:
- What it is: Claude Code keeps its own short notes for each folder you open, without asking.
- Where it lives: on this computer, in ~/.claude/projects/<folder name>/memory/. The first 200 lines of the MEMORY.md file there load at the start of every session in that folder.
- What it may hold: how-to notes about this computer only, such as where a program is installed.
- Which one wins: your Merlin data folder, always. A decision, a preference or a project status goes into the Merlin data folder. When a Claude memory disagrees with a file there, the file wins and the memory gets corrected.
- Merlin does not move or change Claude's memory folder."""


# ------------------------------------------------------------------ paths

def home(*parts):
    return os.path.join(os.path.expanduser('~'), *parts)


POINTER = home('.merlin', 'instance.json')
RECORD = home('.merlin', 'setup-record.json')
SETTINGS = home('.claude', 'settings.json')
CODEX_DIR = home('.codex')
CODEX_AGENTS = home('.codex', 'AGENTS.md')


def plugin_root(explicit=None):
    if explicit:
        return os.path.abspath(explicit)
    d = os.path.dirname(os.path.abspath(__file__))
    while True:
        if os.path.isfile(os.path.join(d, '.claude-plugin', 'plugin.json')):
            return d
        nxt = os.path.dirname(d)
        if nxt == d:
            return None
        d = nxt


def canon(p):
    """Absolute, with ~ expanded, symlinks resolved through the deepest existing folder."""
    p = os.path.abspath(os.path.expanduser(p))
    head, tail = p, []
    while not os.path.exists(head):
        head, t = os.path.split(head)
        if not t:
            break
        tail.insert(0, t)
    return os.path.join(os.path.realpath(head), *tail)


def read_pointer():
    try:
        with open(POINTER, encoding='utf-8') as f:
            return json.load(f)
    except (OSError, ValueError):
        return None


def data_folder(arg):
    if arg and not arg.startswith('${') and arg.strip():
        return canon(arg.strip()), 'option'
    ptr = read_pointer()
    if ptr and ptr.get('data_root'):
        return canon(ptr['data_root']), 'pointer'
    return None, None


def sha256_file(p):
    with open(p, 'rb') as f:
        return hashlib.sha256(f.read()).hexdigest()


def load_record():
    try:
        with open(RECORD, encoding='utf-8') as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def save_record(rec):
    os.makedirs(os.path.dirname(RECORD), exist_ok=True)
    tmp = RECORD + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as f:
        json.dump(rec, f, indent=2)
        f.write('\n')
    os.replace(tmp, RECORD)


def stamp():
    return datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%SZ')


def writable_dir(d):
    return os.path.isdir(d) and os.access(d, os.W_OK | os.X_OK)


def say(line=''):
    print(line)


# ------------------------------------------------------------------ checks

def pointer_check(data):
    """Report only. Never writes the pointer: the start-up hook owns it."""
    ptr = read_pointer()
    if ptr is None:
        if os.path.exists(POINTER):
            return 'problem', 'The pointer file ~/.merlin/instance.json exists but cannot be read. The start-up hook rewrites it at the next session start.'
        return 'missing', 'The pointer file ~/.merlin/instance.json does not exist yet. The start-up hook writes it at the next session start, once the data folder exists.'
    named = ptr.get('data_root')
    if data and named and canon(named) == data:
        return 'ok', 'The pointer file ~/.merlin/instance.json names this data folder.'
    return 'mismatch', 'The pointer file ~/.merlin/instance.json names %s, not this data folder. Start a new session: the start-up hook rewrites it from the plugin setting.' % named


def settings_has(data):
    try:
        with open(SETTINGS, encoding='utf-8') as f:
            s = json.load(f)
    except (OSError, ValueError):
        return False
    dirs = (s.get('permissions') or {}).get('additionalDirectories') or []
    return any(isinstance(x, str) and canon(x) == data for x in dirs)


def codex_status():
    present = os.path.isdir(CODEX_DIR)
    installed = False
    cache = os.path.join(CODEX_DIR, 'plugins', 'cache')
    if os.path.isdir(cache):
        for mkt in os.listdir(cache):
            if os.path.isdir(os.path.join(cache, mkt, 'merlin')):
                installed = True
    trusted = False
    try:
        with open(os.path.join(CODEX_DIR, 'config.toml'), encoding='utf-8') as f:
            trusted = bool(CODEX_TRUST_RE.search(f.read()))
    except OSError:
        pass
    block = False
    try:
        with open(CODEX_AGENTS, encoding='utf-8') as f:
            block = CODEX_BEGIN in f.read()
    except OSError:
        pass
    return {'codex': present, 'merlin_installed': installed, 'hook_trusted': trusted, 'block_present': block}


# ------------------------------------------------------------------ skeleton

def copy_skeleton(root, data):
    """Copy skeleton/ into the data folder. Never overwrites a file that exists."""
    src = os.path.join(root, 'skeleton')
    if not os.path.isdir(src):
        raise SystemExit('setup: the starter files are missing from the plugin folder (%s). Reinstall the plugin.' % src)
    parent = os.path.dirname(data)
    if not os.path.isdir(data):
        if not writable_dir(parent):
            raise SystemExit('setup: read-only. The data folder %s does not exist and its parent folder cannot be written. Nothing was written.' % data)
        os.makedirs(data)
    if not writable_dir(data):
        raise SystemExit('setup: read-only. This computer account cannot write to %s. Nothing was written.' % data)
    created, kept = [], []
    for dirpath, dirnames, filenames in os.walk(src):
        dirnames.sort()
        rel_dir = os.path.relpath(dirpath, src)
        target_dir = data if rel_dir == '.' else os.path.join(data, rel_dir)
        if not os.path.isdir(target_dir):
            os.makedirs(target_dir)
            created.append(os.path.relpath(target_dir, data) + '/')
        for name in sorted(filenames):
            if name == '.DS_Store':
                continue
            s = os.path.join(dirpath, name)
            t = os.path.join(target_dir, name)
            rel = os.path.relpath(t, data)
            if os.path.lexists(t):
                kept.append(rel)
                continue
            with open(s, encoding='utf-8') as f:
                lines = [ln for ln in f.read().split('\n') if not ln.startswith(BUILD_MARKER)]
            fd = os.open(t, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
            with os.fdopen(fd, 'w', encoding='utf-8') as f:
                f.write('\n'.join(lines))
            created.append(rel)
    return created, kept


# ------------------------------------------------------------------ settings grant

def grant(data, yes):
    if settings_has(data):
        say('Folder access: already granted. ~/.claude/settings.json lists %s. Nothing to change.' % data)
        return 0
    exists = os.path.exists(SETTINGS)
    if exists:
        try:
            with open(SETTINGS, encoding='utf-8') as f:
                settings = json.load(f)
        except ValueError:
            say('Folder access: ~/.claude/settings.json is not valid JSON, so setup will not edit it. Nothing was written.')
            return 2
        if not isinstance(settings, dict):
            say('Folder access: ~/.claude/settings.json is not a JSON object. Nothing was written.')
            return 2
    else:
        settings = {}
    perms = settings.get('permissions')
    if perms is not None and not isinstance(perms, dict):
        say('Folder access: "permissions" in ~/.claude/settings.json is not an object. Nothing was written.')
        return 2
    say('Folder access: setup will add one line to ~/.claude/settings.json, under permissions.additionalDirectories:')
    say('  "%s"' % data)
    say('This lets a session opened in one of your project folders read and write the whole Merlin data folder. Nothing else in the file changes.')
    if not yes:
        say('Preview only. Nothing was written. Run again with --yes after the user says yes.')
        return 0
    backups = os.path.join(data, 'state', 'setup', 'backups')
    if not writable_dir(data):
        say('Folder access: read-only. The data folder cannot be written, so no backup can be kept. Nothing was written.')
        return 2
    backup = None
    if exists:
        os.makedirs(backups, exist_ok=True)
        backup = os.path.join(backups, 'claude-settings.json.%s' % stamp())
        shutil.copy2(SETTINGS, backup)
    created_perms = perms is None
    if created_perms:
        perms = {}
        settings['permissions'] = perms
    dirs = perms.get('additionalDirectories')
    created_dirs = dirs is None
    if created_dirs:
        dirs = []
    dirs = list(dirs) + [data]
    perms['additionalDirectories'] = dirs
    os.makedirs(os.path.dirname(SETTINGS), exist_ok=True)
    tmp = SETTINGS + '.merlin-tmp'
    with open(tmp, 'w', encoding='utf-8') as f:
        json.dump(settings, f, indent=2)
        f.write('\n')
    os.replace(tmp, SETTINGS)
    rec = load_record()
    rec['settings'] = {'added': data, 'created_file': not exists, 'created_permissions': created_perms,
                       'created_additional': created_dirs, 'backup': backup,
                       'written_sha256': sha256_file(SETTINGS)}
    save_record(rec)
    say('Folder access: added. %s' % ('Backup of the previous file: %s' % backup if backup else 'The file did not exist before; setup created it.'))
    return 0


# ------------------------------------------------------------------ Codex block

def codex_block_text(data):
    return '\n'.join([
        CODEX_BEGIN,
        '## Merlin',
        '',
        'Merlin is installed for this account. Your Merlin data folder is `%s`.' % data,
        'Before other Merlin work in a session, run the Merlin `rules` skill and follow it.',
        'Your Merlin data folder wins over any memory the assistant keeps.',
        CODEX_END,
        '',
    ])


def codex_block(data, yes):
    st = codex_status()
    if not st['codex']:
        say('Codex: not found on this computer (~/.codex is missing). Nothing to do.')
        return 0
    if st['hook_trusted']:
        say('Codex: Merlin\'s start-up hook is already trusted in Codex, so the rules load on their own. No block is needed.')
        return 0
    if st['block_present']:
        say('Codex: the Merlin block is already in ~/.codex/AGENTS.md. Nothing to change.')
        return 0
    text = codex_block_text(data)
    say('Codex: setup will add this block at the end of ~/.codex/AGENTS.md, between two marker lines, and change nothing else:')
    say(text)
    if not yes:
        say('Preview only. Nothing was written. Run again with --yes after the user says yes.')
        return 0
    existed = os.path.exists(CODEX_AGENTS)
    old = ''
    if existed:
        with open(CODEX_AGENTS, encoding='utf-8') as f:
            old = f.read()
    sep = '' if (not old or old.endswith('\n\n')) else ('\n' if old.endswith('\n') else '\n\n')
    with open(CODEX_AGENTS, 'a', encoding='utf-8') as f:
        f.write(sep + text)
    rec = load_record()
    rec['codex'] = {'created_file': not existed, 'separator': sep}
    save_record(rec)
    say('Codex: block added to ~/.codex/AGENTS.md.')
    return 0


# ------------------------------------------------------------------ Keychain

def key_store(name):
    if not re.match(r'^[A-Za-z0-9_.-]+$', name):
        say('Keys: the key name may use letters, digits, dot, dash and underscore only. Nothing was stored.')
        return 2
    value = sys.stdin.read().rstrip('\n')
    if not value:
        say('Keys: no value was given on standard input. Nothing was stored.')
        return 2
    r = subprocess.run(['security', 'add-generic-password', '-a', name, '-s', KEYCHAIN_SERVICE, '-U', '-w', value],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    value = None
    if r.returncode != 0:
        say('Keys: the macOS Keychain refused to store %s (exit %d). Nothing was stored.' % (name, r.returncode))
        return 1
    rec = load_record()
    keys = set(rec.get('keys') or [])
    keys.add(name)
    rec['keys'] = sorted(keys)
    save_record(rec)
    say('Keys: %s stored in the macOS Keychain under service "%s". The value was not printed.' % (name, KEYCHAIN_SERVICE))
    return 0


def key_check(name):
    r = subprocess.run(['security', 'find-generic-password', '-a', name, '-s', KEYCHAIN_SERVICE],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print('ok' if r.returncode == 0 else 'missing')
    return 0


# ------------------------------------------------------------------ remove

def remove(data, yes, keys):
    rec = load_record()
    plan = []
    if os.path.exists(POINTER):
        plan.append('delete the pointer file ~/.merlin/instance.json')
    s = rec.get('settings')
    if s:
        plan.append('take %s back out of ~/.claude/settings.json' % s['added'])
    elif data and settings_has(data):
        plan.append('leave the folder-access line for %s in ~/.claude/settings.json: setup has no record of adding it' % data)
    c = rec.get('codex')
    has_block = False
    try:
        with open(CODEX_AGENTS, encoding='utf-8') as f:
            has_block = CODEX_BEGIN in f.read()
    except OSError:
        pass
    if has_block:
        plan.append('remove the Merlin block from ~/.codex/AGENTS.md')
    for k in keys:
        plan.append('delete the Keychain key %s (service "%s")' % (k, KEYCHAIN_SERVICE))
    if os.path.exists(RECORD):
        plan.append('delete setup\'s own record, ~/.merlin/setup-record.json')
    say('Remove: this reverses what Merlin wrote outside your Merlin data folder.')
    if not plan:
        say('Nothing to remove.')
    for i, p in enumerate(plan, 1):
        say('  %d. %s' % (i, p))
    say('Your Merlin data folder and every file in it stay exactly as they are%s.' % (' (%s)' % data if data else ''))
    if not yes:
        say('Preview only. Nothing was changed. Run again with --yes after the user says yes.')
        return 0

    if s and os.path.exists(SETTINGS):
        same = sha256_file(SETTINGS) == s.get('written_sha256')
        if same and s.get('created_file'):
            os.remove(SETTINGS)
            say('Folder access: removed. Setup had created ~/.claude/settings.json and nothing else changed it since, so it was deleted.')
        elif same and s.get('backup') and os.path.exists(s['backup']):
            shutil.copyfile(s['backup'], SETTINGS)
            say('Folder access: removed. ~/.claude/settings.json is back to the copy saved before setup changed it.')
        else:
            try:
                with open(SETTINGS, encoding='utf-8') as f:
                    settings = json.load(f)
            except ValueError:
                say('Folder access: ~/.claude/settings.json is not valid JSON now, so setup did not edit it. Remove the line for %s by hand.' % s['added'])
                settings = None
            if settings is not None:
                perms = settings.get('permissions') or {}
                dirs = perms.get('additionalDirectories') or []
                keep = [x for x in dirs if not (isinstance(x, str) and canon(x) == s['added'])]
                if keep or not s.get('created_additional'):
                    perms['additionalDirectories'] = keep
                else:
                    perms.pop('additionalDirectories', None)
                if 'permissions' in settings and not perms and s.get('created_permissions'):
                    settings.pop('permissions')
                if not settings and s.get('created_file'):
                    os.remove(SETTINGS)
                else:
                    tmp = SETTINGS + '.merlin-tmp'
                    with open(tmp, 'w', encoding='utf-8') as f:
                        json.dump(settings, f, indent=2)
                        f.write('\n')
                    os.replace(tmp, SETTINGS)
                say('Folder access: removed the line for %s. The rest of ~/.claude/settings.json was kept; it had changed since setup.' % s['added'])
    if has_block:
        with open(CODEX_AGENTS, encoding='utf-8') as f:
            text = f.read()
        a = text.index(CODEX_BEGIN)
        b = text.index(CODEX_END, a) + len(CODEX_END)
        if text[b:b + 1] == '\n':
            b += 1
        sep = (c or {}).get('separator', '')
        if sep and text[a - len(sep):a] == sep:
            a -= len(sep)
        rest = text[:a] + text[b:]
        if not rest.strip() and (c or {}).get('created_file'):
            os.remove(CODEX_AGENTS)
        else:
            with open(CODEX_AGENTS, 'w', encoding='utf-8') as f:
                f.write(rest)
        say('Codex: the Merlin block was removed from ~/.codex/AGENTS.md.')
    for k in keys:
        r = subprocess.run(['security', 'delete-generic-password', '-a', k, '-s', KEYCHAIN_SERVICE],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        say('Keys: %s %s.' % (k, 'deleted' if r.returncode == 0 else 'was not in the Keychain'))
    if os.path.exists(POINTER):
        os.remove(POINTER)
        say('Pointer: ~/.merlin/instance.json deleted.')
    if os.path.exists(RECORD):
        os.remove(RECORD)
    try:
        os.rmdir(home('.merlin'))
    except OSError:
        pass
    say('Next: uninstall the plugin straight away (in Claude Code: /plugin, or claude plugin uninstall in a terminal). '
        'While it stays installed, its start-up hook writes the pointer file again at the next session start.')
    return 0


# ------------------------------------------------------------------ report

def report(root, data, source, created=None, kept=None):
    say('Merlin setup report')
    say('')
    checks = []
    if data is None:
        checks.append(('missing', 'Merlin data folder: none chosen. Set the plugin option "Your Merlin data folder", then start a new session.'))
    else:
        checks.append(('ok' if os.path.isdir(data) else 'missing', 'Merlin data folder: %s (from the %s)' % (data, 'plugin setting' if source == 'option' else 'pointer file')))
        if os.path.isdir(data):
            checks.append(('ok' if writable_dir(data) else 'problem', 'Writable by this account' if writable_dir(data) else 'Not writable by this account: Merlin stays read-only'))
            needed = ['manifest.yaml', 'TASKS.md', 'ABOUT-ME', 'memory', '.task-ids', 'state']
            missing = [n for n in needed if not os.path.exists(os.path.join(data, n))]
            checks.append(('ok' if not missing else 'missing', 'Starter files: in place' if not missing else 'Starter files missing: %s' % ', '.join(missing)))
            have_about = os.path.exists(os.path.join(data, 'ABOUT-ME', 'about-me.md'))
            checks.append(('ok' if have_about else 'missing', 'About you: ABOUT-ME/about-me.md %s' % ('exists' if have_about else 'not written yet (the about-me interview writes it)')))
        status, msg = pointer_check(data)
        checks.append(('problem' if status == 'mismatch' else status, msg))
        checks.append(('ok' if settings_has(data) else 'optional', 'Folder access in ~/.claude/settings.json: %s' % ('granted' if settings_has(data) else 'not granted (offered on a yes)')))
    cs = codex_status()
    if cs['codex']:
        checks.append(('ok' if (cs['hook_trusted'] or cs['block_present']) else 'optional',
                       'Codex: %s' % ('start-up hook trusted' if cs['hook_trusted'] else ('Merlin block in ~/.codex/AGENTS.md' if cs['block_present'] else 'hook not trusted and no block (the block is offered on a yes)'))))
    if created is not None:
        checks.append(('ok', 'Starter files copied now: %d created, %d already there and left as they were' % (len(created), len(kept))))
    for st, msg in checks:
        mark = {'ok': '[ok]', 'missing': '[missing]', 'problem': '[problem]', 'optional': '[optional]'}[st]
        say('%-10s %s' % (mark, msg))
    say('')
    say(MEMORY_NOTE)
    say('')
    nxt = next((m for s, m in checks if s in ('missing', 'problem')), None)
    say('Next action: %s' % (nxt if nxt else 'nothing is missing. Start your first project with Merlin\'s project-setup command.'))
    return 0


# ------------------------------------------------------------------ main

def main(argv):
    ap = argparse.ArgumentParser(prog='setup', add_help=True)
    ap.add_argument('--data')
    ap.add_argument('--plugin-root')
    ap.add_argument('--yes', action='store_true')
    ap.add_argument('--keys', default='')
    g = ap.add_mutually_exclusive_group()
    for m in ('check', 'skeleton-only', 'skeleton', 'grant', 'codex-status', 'codex-block', 'explain-memory', 'remove'):
        g.add_argument('--' + m, action='store_true')
    g.add_argument('--key-store', metavar='NAME')
    g.add_argument('--key-check', metavar='NAME')
    a = ap.parse_args(argv)
    root = plugin_root(a.plugin_root)
    data, source = data_folder(a.data)

    if a.explain_memory:
        say(MEMORY_NOTE)
        return 0
    if a.key_store:
        return key_store(a.key_store)
    if a.key_check:
        return key_check(a.key_check)
    if a.codex_status:
        say(json.dumps(codex_status(), indent=2))
        return 0
    if a.remove:
        return remove(data, a.yes, [k for k in a.keys.split(',') if k])
    if data is None and not a.check:
        say('setup: no Merlin data folder is known. Set the plugin option "Your Merlin data folder", start a new session, then run setup again. Nothing was written.')
        return 2
    if a.grant:
        return grant(data, a.yes)
    if a.codex_block:
        return codex_block(data, a.yes)
    if a.skeleton or a.skeleton_only:
        if root is None:
            say('setup: cannot find the plugin folder from %s. Nothing was written.' % __file__)
            return 2
        created, kept = copy_skeleton(root, data)
        return report(root, data, source, created, kept)
    return report(root, data, source)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
