#!/usr/bin/env python3
"""Merlin setup helper. Run through setup.sh, which checks python3 first.

Every change outside the business folder is recorded in ~/.merlin/setup-record.json,
so `--remove` reverses exactly what setup added and nothing else. Honours a HOME
override (every home path comes from os.path.expanduser). Never reads a plugin variable:
the plugin folder is found from this file's own location.

Modes (one per run):
  --check                 report only; writes nothing anywhere
  --suggest [NAME]        print the folders to offer, in order. First the open folder (the
                          working folder, or --open DIR) unless it is home, Desktop, Documents or
                          Downloads itself, the top of a synced folder, a system or hidden folder,
                          a folder named Merlin, or inside another business folder. Then
                          <Dropbox>/<NAME>, or ~/Documents/<NAME> with no Dropbox (My Business
                          when no usable name is given). Reports a prepared folder (one that
                          already holds Merlin's starter files). Writes nothing.
                          --offer-drive-icloud also lets Google Drive, then iCloud Drive, be
                          suggested when Dropbox is absent; off until they are tested.
  --inspect DIR           report what DIR already holds (a prepared folder's business name and
                          what is filled in; when Praxis left its record in
                          state/praxis-concierge/prepared.json, also the date, the owner's
                          first name and the open tasks). Writes nothing.
  --choose DIR [--yes]    record DIR as the business folder: create it if needed and
                          write the pointer ~/.merlin/instance.json (preview without --yes).
                          Refuses when --data (the plugin option) names a different folder.
  --skeleton-only         copy the starter files into the business folder (never overwrites),
                          then report; no questions, no settings changes
  --skeleton [--name N]   same copy, used by the interactive setup; N, the business name,
                          goes into a manifest.yaml this run creates
  --set-name NAME         write NAME into manifest.yaml, only where it still reads
                          `name: My Business`; a name already there is never changed
  --grant [--yes]         add the business folder to permissions.additionalDirectories in
                          ~/.claude/settings.json (preview without --yes; backup first)
  --codex-status          report Codex: installed, Merlin present, start-up hook trusted
  --codex-block [--yes]   add the managed Merlin block to ~/.codex/AGENTS.md (preview
                          without --yes)
  --key-store NAME        store a key in the macOS Keychain, service "Merlin"; the value
                          is read from stdin and never printed
  --key-check NAME        print "ok" or "missing", never the value
  --explain-memory        print the plain-words note about Claude Code's own memory
  --remove [--yes] [--keys A,B]
                          reverse what setup and the start-up hook wrote outside the
                          business folder (preview without --yes); never touches that folder
Common: --data DIR, the plugin option (default: the folder named in ~/.merlin/instance.json)

Who writes the pointer: merlin:setup (--choose), after the user's yes in chat, and the
start-up hook, only while the plugin option is set. The option wins when both exist.
"""

import argparse
import datetime
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys

BUILD_MARKER = '<!-- Generated by the plugin build.'
KEYCHAIN_SERVICE = 'Merlin'
CODEX_BEGIN = '<!-- BEGIN MERLIN (managed by merlin:setup; remove with merlin:setup --remove) -->'
CODEX_END = '<!-- END MERLIN -->'
CODEX_TRUST_RE = re.compile(r'^\[hooks\.state\."[^"]*/merlin/[^"]*hooks\.json:session_start:', re.M)

MEMORY_NOTE = """Claude's own memory, in plain words:
- What it is: Claude Code keeps its own short notes for each folder you open, without asking.
- Where it lives: on this computer, in ~/.claude/projects/<folder name>/memory/. The first 200 lines of the MEMORY.md file there load at the start of every session in that folder.
- What it may hold: how-to notes about this computer only, such as where a program is installed.
- Which one wins: your business folder, always. A decision, a preference or a project status goes into the business folder. When a Claude memory disagrees with a file there, the file wins and the memory gets corrected.
- Merlin does not move or change Claude's memory folder."""


# ------------------------------------------------------------------ paths

def home(*parts):
    return os.path.join(os.path.expanduser('~'), *parts)


POINTER = home('.merlin', 'instance.json')
RECORD = home('.merlin', 'setup-record.json')
SETTINGS = home('.claude', 'settings.json')
CODEX_DIR = home('.codex')
CODEX_AGENTS = home('.codex', 'AGENTS.md')


def plugin_root(explicit=None):
    if explicit:
        return os.path.abspath(explicit)
    d = os.path.dirname(os.path.abspath(__file__))
    while True:
        if os.path.isfile(os.path.join(d, '.claude-plugin', 'plugin.json')):
            return d
        nxt = os.path.dirname(d)
        if nxt == d:
            return None
        d = nxt


def canon(p):
    """Absolute, with ~ expanded, symlinks resolved through the deepest existing folder."""
    p = os.path.abspath(os.path.expanduser(p))
    head, tail = p, []
    while not os.path.exists(head):
        head, t = os.path.split(head)
        if not t:
            break
        tail.insert(0, t)
    return os.path.join(os.path.realpath(head), *tail)


def read_pointer():
    try:
        with open(POINTER, encoding='utf-8') as f:
            return json.load(f)
    except (OSError, ValueError):
        return None


def data_folder(arg):
    if arg and not arg.startswith('${') and arg.strip():
        return canon(arg.strip()), 'option'
    ptr = read_pointer()
    if ptr and ptr.get('data_root'):
        return canon(ptr['data_root']), 'pointer'
    return None, None


def sha256_file(p):
    with open(p, 'rb') as f:
        return hashlib.sha256(f.read()).hexdigest()


def load_record():
    try:
        with open(RECORD, encoding='utf-8') as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def save_record(rec):
    os.makedirs(os.path.dirname(RECORD), exist_ok=True)
    tmp = RECORD + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as f:
        json.dump(rec, f, indent=2)
        f.write('\n')
    os.replace(tmp, RECORD)


def stamp():
    return datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%SZ')


def writable_dir(d):
    return os.path.isdir(d) and os.access(d, os.W_OK | os.X_OK)


def say(line=''):
    print(line)


# ------------------------------------------------------------------ checks

def pointer_check(data):
    """Report only. The pointer is written by --choose, or by the start-up hook while the
    plugin option is set."""
    ptr = read_pointer()
    if ptr is None:
        if os.path.exists(POINTER):
            return 'problem', 'The pointer file ~/.merlin/instance.json exists but cannot be read. Run setup\'s folder step to record the business folder again.'
        return 'missing', 'The pointer file ~/.merlin/instance.json does not exist yet. Run setup\'s folder step to record this business folder.'
    named = ptr.get('data_root')
    if data and named and canon(named) == data:
        return 'ok', 'The pointer file ~/.merlin/instance.json names this business folder.'
    return 'mismatch', 'The pointer file ~/.merlin/instance.json names %s, not this business folder. The plugin setting wins: the start-up hook rewrites the pointer from it at the next session start.' % named


def settings_has(data):
    try:
        with open(SETTINGS, encoding='utf-8') as f:
            s = json.load(f)
    except (OSError, ValueError):
        return False
    dirs = (s.get('permissions') or {}).get('additionalDirectories') or []
    return any(isinstance(x, str) and canon(x) == data for x in dirs)


def codex_status():
    present = os.path.isdir(CODEX_DIR)
    installed = False
    cache = os.path.join(CODEX_DIR, 'plugins', 'cache')
    if os.path.isdir(cache):
        for mkt in os.listdir(cache):
            if os.path.isdir(os.path.join(cache, mkt, 'merlin')):
                installed = True
    trusted = False
    try:
        with open(os.path.join(CODEX_DIR, 'config.toml'), encoding='utf-8') as f:
            trusted = bool(CODEX_TRUST_RE.search(f.read()))
    except OSError:
        pass
    block = False
    try:
        with open(CODEX_AGENTS, encoding='utf-8') as f:
            block = CODEX_BEGIN in f.read()
    except OSError:
        pass
    return {'codex': present, 'merlin_installed': installed, 'hook_trusted': trusted, 'block_present': block}


# ------------------------------------------------------------------ choose

def plugin_version(root):
    try:
        with open(os.path.join(root, '.claude-plugin', 'plugin.json'), encoding='utf-8') as f:
            return json.load(f).get('version') or 'unknown'
    except (OSError, ValueError, TypeError):
        return 'unknown'


def nearest_existing(p):
    while not os.path.exists(p):
        nxt = os.path.dirname(p)
        if nxt == p:
            break
        p = nxt
    return p


FALLBACK_NAME = 'My Business'


def suggest_name(name):
    """The folder name to suggest for a business: its own name, made safe as one folder name.

    The folder holds the whole business (about-me, memory, tasks, every project), so it is
    named after the business and never after Merlin: a folder named after the tool reads as
    deletable when the tool is removed. Falls back to FALLBACK_NAME.
    """
    n = ''.join(' ' if (ch in '/:\\' or ord(ch) < 32) else ch for ch in (name or ''))
    n = ' '.join(n.split()).strip(' .')
    if len(n) > 60:
        n = n[:60].rstrip(' .')
    if not n or n.casefold() == 'merlin':
        return FALLBACK_NAME
    return n


def is_within(p, parent):
    return p == parent or p.startswith(parent.rstrip(os.sep) + os.sep)


def tilde(p):
    h = canon(home())
    return '~' + p[len(h):] if is_within(p, h) and p != h else ('~' if p == h else p)


def dropbox_roots():
    """Every Dropbox folder on this Mac, real paths, the plain `Dropbox` folder first."""
    cands = []
    cs = home('Library', 'CloudStorage')
    if os.path.isdir(cs):
        cands += [os.path.join(cs, n) for n in sorted(os.listdir(cs))
                  if n.startswith('Dropbox') and os.path.isdir(os.path.join(cs, n))]
    if os.path.isdir(home('Dropbox')):
        cands.append(home('Dropbox'))
    out = []
    for c in cands:
        r = canon(c)
        if r not in out:
            out.append(r)
    return sorted(out, key=lambda r: os.path.basename(r) != 'Dropbox')


def drive_roots():
    cs = home('Library', 'CloudStorage')
    if not os.path.isdir(cs):
        return []
    return [canon(os.path.join(cs, n, 'My Drive')) for n in sorted(os.listdir(cs))
            if n.startswith('GoogleDrive-') and os.path.isdir(os.path.join(cs, n, 'My Drive'))]


def icloud_root():
    p = home('Library', 'Mobile Documents', 'com~apple~CloudDocs')
    return canon(p) if os.path.isdir(p) else None


def backed_up_place(drive_icloud):
    """(service, folder) to suggest the business folder in, or (None, None).

    Dropbox always comes first. Google Drive and iCloud Drive can keep files online-only, and
    neither has been tested with Merlin yet, so they count only with --offer-drive-icloud.
    """
    dbx = dropbox_roots()
    if dbx:
        return 'Dropbox', dbx[0]
    if drive_icloud:
        drv = drive_roots()
        if drv:
            return 'Google Drive', drv[0]
        ic = icloud_root()
        if ic:
            return 'iCloud Drive', ic
    return None, None


def service_name(provider):
    for prefix, svc in (('Dropbox', 'Dropbox'), ('GoogleDrive-', 'Google Drive'), ('OneDrive', 'OneDrive')):
        if provider.startswith(prefix):
            return svc
    return provider


PLAIN_PLACES = (('Desktop', 'your Desktop'), ('Documents', 'your Documents folder'), ('Downloads', 'your Downloads folder'))


def library_reason(p):
    """Why a folder inside ~/Library is not offered, or None when it sits inside a synced folder."""
    cs = canon(home('Library', 'CloudStorage'))
    ic = canon(home('Library', 'Mobile Documents', 'com~apple~CloudDocs'))
    if is_within(p, cs) and p != cs:
        parts = os.path.relpath(p, cs).split(os.sep)
        if len(parts) >= (3 if parts[0].startswith('GoogleDrive-') else 2):
            return None
        return 'it is the top of your %s, not a folder inside it' % service_name(parts[0])
    if is_within(p, ic):
        return None if p != ic else 'it is the top of your iCloud Drive, not a folder inside it'
    return "it is one of your Mac's own system folders"


def is_prepared(d):
    """A business folder: Merlin's manifest plus a task list, a claim folder or ABOUT-ME."""
    return os.path.isfile(os.path.join(d, 'manifest.yaml')) and any(
        os.path.exists(os.path.join(d, x)) for x in ('.task-ids', 'TASKS.md', 'ABOUT-ME'))


def enclosing_business(p):
    """The business folder P sits inside (never P itself), or None."""
    ptr = read_pointer() or {}
    named = canon(ptr['data_root']) if ptr.get('data_root') else None
    if named and is_within(p, named) and p != named:
        return named
    parts = p.split(os.sep)
    for i in range(len(parts) - 1, 0, -1):
        above = os.sep.join(parts[:i]) or os.sep
        if is_prepared(above):
            return above
    return None


def open_folder_check(raw):
    """(offered, words): words is the plain place when offered, else the plain reason."""
    if not raw or not raw.strip():
        return False, 'no open folder was given'
    p = canon(raw.strip())
    h = canon(home())
    if not os.path.isdir(p):
        return False, 'it is not a folder on this Mac'
    if p == h:
        return False, 'it is your home folder itself'
    if is_within(h, p):
        return False, 'it holds your whole home folder'
    for d, words in PLAIN_PLACES:
        if p == canon(home(d)):
            return False, 'it is %s itself' % words
    for r in dropbox_roots():
        if p == r:
            return False, 'it is the top of your Dropbox, not a folder inside it'
    if is_within(p, canon(home('Library'))):
        why = library_reason(p)
        if why:
            return False, why
    elif is_within(p, h) and any(x.startswith('.') for x in os.path.relpath(p, h).split(os.sep)):
        return False, 'it is a hidden folder'
    if os.path.basename(p).casefold() == 'merlin':
        return False, 'it is named Merlin, and a folder named after the tool reads as safe to delete when the tool is removed'
    owner = enclosing_business(p)
    if owner:
        return False, 'it is inside another business folder, "%s"' % os.path.basename(owner)
    if not writable_dir(p):
        return False, 'this computer account cannot write to it'
    return True, place_words(p)


def synced_places():
    """[(root, plain words)] for every synced folder found, whatever the switch says."""
    places = [(r, 'your Dropbox') for r in dropbox_roots()] + [(r, 'your Google Drive') for r in drive_roots()]
    ic = icloud_root()
    if ic:
        places.append((ic, 'your iCloud Drive'))
    return places


def in_synced(p):
    return any(is_within(p, r) for r, _ in synced_places())


def place_words(p):
    """'"Acmeco" on your Desktop', in plain words, never a path."""
    name, parent = os.path.basename(p), os.path.dirname(p)
    for d, words in PLAIN_PLACES:
        if parent == canon(home(d)):
            return '"%s" %s' % (name, 'on your Desktop' if d == 'Desktop' else 'in %s' % words)
    if parent == canon(home()):
        return '"%s" in your home folder' % name
    for r, words in synced_places():
        if parent == r:
            return '"%s" in %s' % (name, words)
        if is_within(parent, r):
            return '"%s" in the folder "%s" in %s' % (name, os.path.basename(parent), words)
    return '"%s" in the folder "%s"' % (name, os.path.basename(parent) or parent)


def manifest_name(d):
    try:
        with open(os.path.join(d, 'manifest.yaml'), encoding='utf-8') as f:
            text = f.read()
    except OSError:
        return None
    m = re.search(r'^name:[ \t]*(.+?)[ \t]*$', text, re.M)
    if not m:
        return None
    v = m.group(1)
    q = re.match(r'"((?:[^"\\]|\\.)*)"', v)
    if q:
        try:
            v = json.loads(q.group(0))
        except ValueError:
            v = q.group(1)
    else:
        v = re.sub(r'\s+#.*$', '', v).strip("'")
    return v.strip() or None


RECEIPT = os.path.join('state', 'praxis-concierge', 'prepared.json')
NAME_PLACEHOLDERS = ('name: %s' % FALLBACK_NAME, 'name: %s' % json.dumps(FALLBACK_NAME))


def read_receipt(d):
    """The record Praxis leaves in a folder it prepared, as (date, first name or None), or None.

    A missing, unreadable, truncated or odd-shaped record counts as no record at all, so the
    report is then exactly what it is for any prepared folder.
    """
    try:
        with open(os.path.join(d, RECEIPT), encoding='utf-8') as f:
            rec = json.load(f)
    except (OSError, ValueError):
        return None
    if not isinstance(rec, dict):
        return None
    when = rec.get('prepared_on')
    if not isinstance(when, str) or not re.match(r'^\d{4}-\d{2}-\d{2}$', when):
        return None
    try:
        datetime.date.fromisoformat(when)
    except ValueError:
        return None
    first = rec.get('owner_first_name')
    first = ' '.join(first.split()) if isinstance(first, str) else ''
    return when, first or None


def open_tasks(d):
    """Open tasks on the folder's task list: the live `- [ ]` lines in TASKS.md."""
    try:
        with open(os.path.join(d, 'TASKS.md'), encoding='utf-8') as f:
            text = f.read()
    except (OSError, ValueError):
        return 0
    text = re.sub(r'<!--.*?-->', '', text, flags=re.S)
    return len(re.findall(r'^- \[ \] ', text, re.M))


def prepared_lines(d):
    """What a prepared business folder already holds, one line each."""
    receipt = read_receipt(d)
    if receipt:
        lines = ['Prepared folder: yes. It already holds Merlin\'s starter files, so it was set up before, '
                 'by Praxis. Setup keeps every file in it and fills in only what is missing.']
        when, first = receipt
        lines.append('Prepared by Praxis on %s%s' % (when, ' for %s' % first if first else ''))
    else:
        lines = ['Prepared folder: yes. It already holds Merlin\'s starter files, so it was set up before, '
                 'possibly by Praxis. Setup keeps every file in it and fills in only what is missing.']
    name = manifest_name(d)
    if name and name != FALLBACK_NAME:
        lines.append('Business name in this folder: %s' % name)
    filled = []
    if os.path.isfile(os.path.join(d, 'ABOUT-ME', 'about-me.md')):
        filled.append('notes about you')
    notes = 0
    for dirpath, _, files in os.walk(os.path.join(d, 'memory')):
        notes += sum(1 for f in files if f.endswith('.md') and f != 'README.md')
    if notes:
        filled.append('%d company note%s' % (notes, '' if notes == 1 else 's'))
    try:
        with open(os.path.join(d, 'manifest.yaml'), encoding='utf-8') as f:
            projects = len(re.findall(r'^\s+-\s+name:', f.read(), re.M))
    except OSError:
        projects = 0
    if projects:
        filled.append('%d project%s' % (projects, '' if projects == 1 else 's'))
    lines.append('Already filled in: %s' % ('; '.join(filled) if filled else 'nothing yet beyond the starter files'))
    if receipt:
        n = open_tasks(d)
        lines.append('Task list: %s' % ('no open tasks' if n == 0 else '%d open task%s' % (n, '' if n == 1 else 's')))
    return lines


def set_name(data, name):
    """Write the business name into a manifest.yaml that still has the starter name.

    Replaces only the starter line `name: My Business` (or its quoted form). A name that is
    already there is never changed.
    """
    name = ' '.join((name or '').split())
    if not name:
        say('Business name: no name was given. Nothing was written.')
        return 2
    if name == FALLBACK_NAME:
        say('Business name: "%s" is the starter name, not a business name. Nothing was written.' % FALLBACK_NAME)
        return 2
    path = os.path.join(data, 'manifest.yaml')
    try:
        with open(path, encoding='utf-8', newline='') as f:
            text = f.read()
    except (OSError, ValueError):
        say('Business name: there is no readable manifest.yaml in %s, so there is nowhere to write the name. '
            'Run setup\'s starter-files step first. Nothing was written.' % data)
        return 2
    m = re.search(r'^name:[^\r\n]*', text, re.M)
    if not m:
        say('Business name: manifest.yaml in %s has no name line. Nothing was written.' % data)
        return 2
    if m.group(0) not in NAME_PLACEHOLDERS:
        have = manifest_name(data)
        if have == name:
            say('Business name: already "%s". Nothing to change.' % name)
            return 0
        say('Business name: this folder already has a name, "%s". Setup never changes a name that is '
            'already there, so nothing was written. To change it, edit the name line in manifest.yaml.' % have)
        return 2
    if not os.access(path, os.W_OK) or not writable_dir(data):
        say('Business name: read-only. This computer account cannot write manifest.yaml in %s. Nothing was written.' % data)
        return 2
    new = text[:m.start()] + 'name: %s' % json.dumps(name) + text[m.end():]
    tmp = path + '.merlin-tmp'
    with open(tmp, 'w', encoding='utf-8', newline='') as f:
        f.write(new)
    shutil.copymode(path, tmp)
    os.replace(tmp, path)
    if manifest_name(data) != name:
        with open(tmp, 'w', encoding='utf-8', newline='') as f:
            f.write(text)
        shutil.copymode(path, tmp)
        os.replace(tmp, path)
        say('Business name: the name could not be read back the same way, so manifest.yaml was put back as it was.')
        return 1
    say('Business name: set to "%s" in manifest.yaml. Nothing else in the folder changed.' % name)
    return 0


def folder_status(path):
    if not os.path.exists(path):
        return ['It does not exist yet. Setup creates it after the user says yes.']
    if not os.path.isdir(path):
        return ['A file already has that name, so it cannot be the folder. Suggest another name.']
    if is_prepared(path):
        return prepared_lines(path)
    try:
        items = [x for x in os.listdir(path) if not x.startswith('.')]
    except OSError:
        return ['It exists, but this computer account cannot read it. Suggest another folder.']
    if items:
        return ['It exists and holds %d item(s). Setup adds its starter files beside them and overwrites nothing.' % len(items)]
    return ['It exists and is empty.']


ONE_MAC = ('Use the business folder from one Mac at a time: two Macs writing to it at once can leave '
           '"conflicted copy" files.')


def suggest(name, open_dir, drive_icloud):
    """Print the folders to offer, in order: the open folder, then a backed-up place. Writes nothing."""
    folder = suggest_name(name)
    if open_dir is not None:
        offered, words = open_folder_check(open_dir)
        say('Open folder: %s' % (canon(open_dir) if open_dir.strip() else '(none)'))
        if offered:
            say('Open folder offer: yes')
            say('Open folder in plain words: %s' % words)
            for ln in folder_status(canon(open_dir)):
                say(ln)
        else:
            say('Open folder offer: no (%s)' % words)
    svc, base = backed_up_place(drive_icloud)
    if svc:
        path = os.path.join(base, folder)
        say('Backed-up place: %s (%s)' % (svc, tilde(base)))
        say('Suggested business folder: %s' % tilde(path))
        say('Suggested in plain words: a folder named "%s" in your %s, which keeps it backed up.' % (folder, svc))
    else:
        docs = canon(home('Documents'))
        path = os.path.join(docs if os.path.isdir(docs) else canon(home()), folder)
        say('Backed-up place: none found (no Dropbox on this Mac)')
        say('Suggested business folder: %s' % tilde(path))
        say('Suggested in plain words: a folder named "%s" in your %s. Make sure it is backed up, for '
            'example with Time Machine.' % (folder, 'Documents folder' if os.path.isdir(docs) else 'home folder'))
    for ln in folder_status(path):
        say(ln)
    if svc or (open_dir is not None and open_dir.strip() and in_synced(canon(open_dir))):
        say(ONE_MAC)
    say('Never move the business folder after setup records it. If it does move, run setup again to record the new place.')
    return 0


def inspect(target):
    """Report what a folder the user names already holds. Writes nothing."""
    p = canon(target)
    say('Folder: %s' % p)
    if os.path.isdir(p):
        offered, words = open_folder_check(p)
        if not offered:
            say('Not usable as the business folder: %s.' % words)
    for ln in folder_status(p):
        say(ln)
    return 0


def choose(root, target, option, yes):
    """Record TARGET as the business folder: create it and write the pointer."""
    raw = (target or '').strip()
    if not raw:
        say('setup: say which folder to use, for example --choose "~/%s". Nothing was written.' % FALLBACK_NAME)
        return 2
    expanded = os.path.expanduser(raw)
    if not os.path.isabs(expanded):
        say('setup: %s is not a full path. Use a path that starts with / or ~/, for example "~/%s". Nothing was written.' % (raw, FALLBACK_NAME))
        return 2
    want = canon(expanded)
    opt = option.strip() if option and not option.startswith('${') and option.strip() else None
    if opt and canon(opt) != want:
        say('setup: the plugin setting "Your business folder" names %s, and that setting wins. '
            'To use %s instead, change the plugin setting. Nothing was written.' % (canon(opt), want))
        return 2
    if os.path.exists(want) and not os.path.isdir(want):
        say('setup: %s is a file, not a folder. Pick another place. Nothing was written.' % want)
        return 2
    base = nearest_existing(want)
    if not os.path.isdir(want) and not writable_dir(base):
        say('setup: read-only. %s does not exist and %s cannot be written by this account. Nothing was written.' % (want, base))
        return 2
    if os.path.isdir(want) and not writable_dir(want):
        say('setup: read-only. This computer account cannot write to %s. Nothing was written.' % want)
        return 2
    ptr = read_pointer() or {}
    named = canon(ptr['data_root']) if ptr.get('data_root') else None
    steps = []
    if not os.path.isdir(want):
        steps.append('create the folder %s' % want)
    if named == want:
        pass
    elif named:
        steps.append('change the pointer file ~/.merlin/instance.json from %s to %s' % (named, want))
    else:
        steps.append('write the pointer file ~/.merlin/instance.json naming %s' % want)
    say('Business folder: %s' % want)
    if not steps:
        say('Already recorded: the folder exists and the pointer file names it. Nothing to do.')
        return 0
    say('Setup will:')
    for i, st in enumerate(steps, 1):
        say('  %d. %s' % (i, st))
    say('No file inside the folder is changed by this step.')
    if not yes:
        say('Preview only. Nothing was changed. Run again with --yes after the user says yes.')
        return 0
    if not os.path.isdir(want):
        os.makedirs(want)
    os.makedirs(os.path.dirname(POINTER), exist_ok=True)
    body = {
        'data_root': want,
        'praxis_root': want,
        'written_by': 'merlin plugin %s, merlin:setup' % plugin_version(root) if root else 'merlin:setup',
        'written_at': datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
        'data_access': 'local',
    }
    tmp = POINTER + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as f:
        json.dump(body, f, indent=2, ensure_ascii=False)
        f.write('\n')
    os.replace(tmp, POINTER)
    rec = load_record()
    rec['pointer_written'] = True
    save_record(rec)
    say('Done. The folder exists and ~/.merlin/instance.json names it. It counts from now on, in this session too.')
    return 0


# ------------------------------------------------------------------ skeleton

def copy_skeleton(root, data, biz_name=None):
    """Copy skeleton/ into the business folder. Never overwrites a file that exists.

    BIZ_NAME, when given, replaces the default `name:` line in a manifest.yaml this run creates.
    """
    src = os.path.join(root, 'skeleton')
    if not os.path.isdir(src):
        raise SystemExit('setup: the starter files are missing from the plugin folder (%s). Reinstall the plugin.' % src)
    parent = os.path.dirname(data)
    if not os.path.isdir(data):
        if not writable_dir(parent):
            raise SystemExit('setup: read-only. The business folder %s does not exist and its parent folder cannot be written. Nothing was written.' % data)
        os.makedirs(data)
    if not writable_dir(data):
        raise SystemExit('setup: read-only. This computer account cannot write to %s. Nothing was written.' % data)
    created, kept = [], []
    for dirpath, dirnames, filenames in os.walk(src):
        dirnames.sort()
        rel_dir = os.path.relpath(dirpath, src)
        target_dir = data if rel_dir == '.' else os.path.join(data, rel_dir)
        if not os.path.isdir(target_dir):
            os.makedirs(target_dir)
            created.append(os.path.relpath(target_dir, data) + '/')
        for name in sorted(filenames):
            if name == '.DS_Store':
                continue
            s = os.path.join(dirpath, name)
            t = os.path.join(target_dir, name)
            rel = os.path.relpath(t, data)
            if os.path.lexists(t):
                kept.append(rel)
                continue
            with open(s, encoding='utf-8') as f:
                lines = [ln for ln in f.read().split('\n') if not ln.startswith(BUILD_MARKER)]
            if biz_name and rel == 'manifest.yaml':
                lines = ['name: %s' % json.dumps(biz_name) if ln == 'name: %s' % FALLBACK_NAME else ln for ln in lines]
            fd = os.open(t, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
            with os.fdopen(fd, 'w', encoding='utf-8') as f:
                f.write('\n'.join(lines))
            created.append(rel)
    return created, kept


# ------------------------------------------------------------------ settings grant

def grant(data, yes):
    if settings_has(data):
        say('Folder access: already granted. ~/.claude/settings.json lists %s. Nothing to change.' % data)
        return 0
    exists = os.path.exists(SETTINGS)
    if exists:
        try:
            with open(SETTINGS, encoding='utf-8') as f:
                settings = json.load(f)
        except ValueError:
            say('Folder access: ~/.claude/settings.json is not valid JSON, so setup will not edit it. Nothing was written.')
            return 2
        if not isinstance(settings, dict):
            say('Folder access: ~/.claude/settings.json is not a JSON object. Nothing was written.')
            return 2
    else:
        settings = {}
    perms = settings.get('permissions')
    if perms is not None and not isinstance(perms, dict):
        say('Folder access: "permissions" in ~/.claude/settings.json is not an object. Nothing was written.')
        return 2
    say('Folder access: setup will add one line to ~/.claude/settings.json, under permissions.additionalDirectories:')
    say('  "%s"' % data)
    say('This lets a session opened in one of your project folders read and write the whole business folder. Nothing else in the file changes.')
    if not yes:
        say('Preview only. Nothing was written. Run again with --yes after the user says yes.')
        return 0
    backups = os.path.join(data, 'state', 'setup', 'backups')
    if not writable_dir(data):
        say('Folder access: read-only. The business folder cannot be written, so no backup can be kept. Nothing was written.')
        return 2
    backup = None
    if exists:
        os.makedirs(backups, exist_ok=True)
        backup = os.path.join(backups, 'claude-settings.json.%s' % stamp())
        shutil.copy2(SETTINGS, backup)
    created_perms = perms is None
    if created_perms:
        perms = {}
        settings['permissions'] = perms
    dirs = perms.get('additionalDirectories')
    created_dirs = dirs is None
    if created_dirs:
        dirs = []
    dirs = list(dirs) + [data]
    perms['additionalDirectories'] = dirs
    os.makedirs(os.path.dirname(SETTINGS), exist_ok=True)
    tmp = SETTINGS + '.merlin-tmp'
    with open(tmp, 'w', encoding='utf-8') as f:
        json.dump(settings, f, indent=2)
        f.write('\n')
    os.replace(tmp, SETTINGS)
    rec = load_record()
    rec['settings'] = {'added': data, 'created_file': not exists, 'created_permissions': created_perms,
                       'created_additional': created_dirs, 'backup': backup,
                       'written_sha256': sha256_file(SETTINGS)}
    save_record(rec)
    say('Folder access: added. %s' % ('Backup of the previous file: %s' % backup if backup else 'The file did not exist before; setup created it.'))
    return 0


# ------------------------------------------------------------------ Codex block

def codex_block_text(data):
    return '\n'.join([
        CODEX_BEGIN,
        '## Merlin',
        '',
        'Merlin is installed for this account. Your business folder is `%s`.' % data,
        'Before other Merlin work in a session, run the Merlin `rules` skill and follow it.',
        'Your business folder wins over any memory the assistant keeps.',
        CODEX_END,
        '',
    ])


def codex_block(data, yes):
    st = codex_status()
    if not st['codex']:
        say('Codex: not found on this computer (~/.codex is missing). Nothing to do.')
        return 0
    if st['hook_trusted']:
        say('Codex: Merlin\'s start-up hook is already trusted in Codex, so the rules load on their own. No block is needed.')
        return 0
    if st['block_present']:
        say('Codex: the Merlin block is already in ~/.codex/AGENTS.md. Nothing to change.')
        return 0
    text = codex_block_text(data)
    say('Codex: setup will add this block at the end of ~/.codex/AGENTS.md, between two marker lines, and change nothing else:')
    say(text)
    if not yes:
        say('Preview only. Nothing was written. Run again with --yes after the user says yes.')
        return 0
    existed = os.path.exists(CODEX_AGENTS)
    old = ''
    if existed:
        with open(CODEX_AGENTS, encoding='utf-8') as f:
            old = f.read()
    sep = '' if (not old or old.endswith('\n\n')) else ('\n' if old.endswith('\n') else '\n\n')
    with open(CODEX_AGENTS, 'a', encoding='utf-8') as f:
        f.write(sep + text)
    rec = load_record()
    rec['codex'] = {'created_file': not existed, 'separator': sep}
    save_record(rec)
    say('Codex: block added to ~/.codex/AGENTS.md.')
    return 0


# ------------------------------------------------------------------ Keychain

def key_store(name):
    if not re.match(r'^[A-Za-z0-9_.-]+$', name):
        say('Keys: the key name may use letters, digits, dot, dash and underscore only. Nothing was stored.')
        return 2
    value = sys.stdin.read().rstrip('\n')
    if not value:
        say('Keys: no value was given on standard input. Nothing was stored.')
        return 2
    r = subprocess.run(['security', 'add-generic-password', '-a', name, '-s', KEYCHAIN_SERVICE, '-U', '-w', value],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    value = None
    if r.returncode != 0:
        say('Keys: the macOS Keychain refused to store %s (exit %d). Nothing was stored.' % (name, r.returncode))
        return 1
    rec = load_record()
    keys = set(rec.get('keys') or [])
    keys.add(name)
    rec['keys'] = sorted(keys)
    save_record(rec)
    say('Keys: %s stored in the macOS Keychain under service "%s". The value was not printed.' % (name, KEYCHAIN_SERVICE))
    return 0


def key_check(name):
    r = subprocess.run(['security', 'find-generic-password', '-a', name, '-s', KEYCHAIN_SERVICE],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print('ok' if r.returncode == 0 else 'missing')
    return 0


# ------------------------------------------------------------------ remove

def remove(data, yes, keys):
    rec = load_record()
    plan = []
    if os.path.exists(POINTER):
        plan.append('delete the pointer file ~/.merlin/instance.json')
    s = rec.get('settings')
    if s:
        plan.append('take %s back out of ~/.claude/settings.json' % s['added'])
    elif data and settings_has(data):
        plan.append('leave the folder-access line for %s in ~/.claude/settings.json: setup has no record of adding it' % data)
    c = rec.get('codex')
    has_block = False
    try:
        with open(CODEX_AGENTS, encoding='utf-8') as f:
            has_block = CODEX_BEGIN in f.read()
    except OSError:
        pass
    if has_block:
        plan.append('remove the Merlin block from ~/.codex/AGENTS.md')
    for k in keys:
        plan.append('delete the Keychain key %s (service "%s")' % (k, KEYCHAIN_SERVICE))
    if os.path.exists(RECORD):
        plan.append('delete setup\'s own record, ~/.merlin/setup-record.json')
    say('Remove: this reverses what Merlin wrote outside your business folder.')
    if not plan:
        say('Nothing to remove.')
    for i, p in enumerate(plan, 1):
        say('  %d. %s' % (i, p))
    say('Your business folder and every file in it stay exactly as they are%s.' % (' (%s)' % data if data else ''))
    if not yes:
        say('Preview only. Nothing was changed. Run again with --yes after the user says yes.')
        return 0

    if s and os.path.exists(SETTINGS):
        same = sha256_file(SETTINGS) == s.get('written_sha256')
        if same and s.get('created_file'):
            os.remove(SETTINGS)
            say('Folder access: removed. Setup had created ~/.claude/settings.json and nothing else changed it since, so it was deleted.')
        elif same and s.get('backup') and os.path.exists(s['backup']):
            shutil.copyfile(s['backup'], SETTINGS)
            say('Folder access: removed. ~/.claude/settings.json is back to the copy saved before setup changed it.')
        else:
            try:
                with open(SETTINGS, encoding='utf-8') as f:
                    settings = json.load(f)
            except ValueError:
                say('Folder access: ~/.claude/settings.json is not valid JSON now, so setup did not edit it. Remove the line for %s by hand.' % s['added'])
                settings = None
            if settings is not None:
                perms = settings.get('permissions') or {}
                dirs = perms.get('additionalDirectories') or []
                keep = [x for x in dirs if not (isinstance(x, str) and canon(x) == s['added'])]
                if keep or not s.get('created_additional'):
                    perms['additionalDirectories'] = keep
                else:
                    perms.pop('additionalDirectories', None)
                if 'permissions' in settings and not perms and s.get('created_permissions'):
                    settings.pop('permissions')
                if not settings and s.get('created_file'):
                    os.remove(SETTINGS)
                else:
                    tmp = SETTINGS + '.merlin-tmp'
                    with open(tmp, 'w', encoding='utf-8') as f:
                        json.dump(settings, f, indent=2)
                        f.write('\n')
                    os.replace(tmp, SETTINGS)
                say('Folder access: removed the line for %s. The rest of ~/.claude/settings.json was kept; it had changed since setup.' % s['added'])
    if has_block:
        with open(CODEX_AGENTS, encoding='utf-8') as f:
            text = f.read()
        a = text.index(CODEX_BEGIN)
        b = text.index(CODEX_END, a) + len(CODEX_END)
        if text[b:b + 1] == '\n':
            b += 1
        sep = (c or {}).get('separator', '')
        if sep and text[a - len(sep):a] == sep:
            a -= len(sep)
        rest = text[:a] + text[b:]
        if not rest.strip() and (c or {}).get('created_file'):
            os.remove(CODEX_AGENTS)
        else:
            with open(CODEX_AGENTS, 'w', encoding='utf-8') as f:
                f.write(rest)
        say('Codex: the Merlin block was removed from ~/.codex/AGENTS.md.')
    for k in keys:
        r = subprocess.run(['security', 'delete-generic-password', '-a', k, '-s', KEYCHAIN_SERVICE],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        say('Keys: %s %s.' % (k, 'deleted' if r.returncode == 0 else 'was not in the Keychain'))
    if os.path.exists(POINTER):
        os.remove(POINTER)
        say('Pointer: ~/.merlin/instance.json deleted.')
    if os.path.exists(RECORD):
        os.remove(RECORD)
    try:
        os.rmdir(home('.merlin'))
    except OSError:
        pass
    say('Next: remove the Merlin plugin straight away. In the Claude app: the Plugins screen. In a terminal: '
        'claude plugin uninstall merlin@praxis-plugins. If the plugin setting "Your business folder" is set, '
        'the start-up hook writes the pointer file again at the next session start while the plugin stays installed.')
    return 0


# ------------------------------------------------------------------ report

def report(root, data, source, created=None, kept=None):
    say('Merlin setup report')
    say('')
    checks = []
    if data is None:
        checks.append(('missing', 'Business folder: none chosen yet. Run setup\'s folder step: it asks which folder to use and records it.'))
    else:
        where = 'plugin setting' if source == 'option' else 'pointer file'
        if os.path.isdir(data):
            checks.append(('ok', 'Business folder: %s (from the %s)' % (data, where)))
        else:
            checks.append(('missing', 'Business folder: %s (from the %s) is not there. If it was moved or renamed on purpose, %s' % (
                data, where, 'run setup\'s folder step to record the new place.' if source != 'option' else 'change the plugin setting to the new place.')))
        if os.path.isdir(data):
            checks.append(('ok' if writable_dir(data) else 'problem', 'Writable by this account' if writable_dir(data) else 'Not writable by this account: Merlin stays read-only'))
            needed = ['manifest.yaml', 'TASKS.md', 'ABOUT-ME', 'memory', '.task-ids', 'state']
            missing = [n for n in needed if not os.path.exists(os.path.join(data, n))]
            checks.append(('ok' if not missing else 'missing', 'Starter files: in place' if not missing else 'Starter files missing: %s' % ', '.join(missing)))
            have_about = os.path.exists(os.path.join(data, 'ABOUT-ME', 'about-me.md'))
            checks.append(('ok' if have_about else 'missing', 'About you: ABOUT-ME/about-me.md %s' % ('exists' if have_about else 'not written yet (the about-me interview writes it)')))
        status, msg = pointer_check(data)
        checks.append(('problem' if status == 'mismatch' else status, msg))
        checks.append(('ok' if settings_has(data) else 'optional', 'Folder access in ~/.claude/settings.json: %s' % ('granted' if settings_has(data) else 'not granted (offered on a yes)')))
    cs = codex_status()
    if cs['codex']:
        checks.append(('ok' if (cs['hook_trusted'] or cs['block_present']) else 'optional',
                       'Codex: %s' % ('start-up hook trusted' if cs['hook_trusted'] else ('Merlin block in ~/.codex/AGENTS.md' if cs['block_present'] else 'hook not trusted and no block (the block is offered on a yes)'))))
    if created is not None:
        checks.append(('ok', 'Starter files copied now: %d created, %d already there and left as they were' % (len(created), len(kept))))
    for st, msg in checks:
        mark = {'ok': '[ok]', 'missing': '[missing]', 'problem': '[problem]', 'optional': '[optional]'}[st]
        say('%-10s %s' % (mark, msg))
    say('')
    say(MEMORY_NOTE)
    say('')
    nxt = next((m for s, m in checks if s in ('missing', 'problem')), None)
    say('Next action: %s' % (nxt if nxt else 'nothing is missing. Next: set up your first project, a folder inside your business folder for one job, client or area of work.'))
    return 0


# ------------------------------------------------------------------ main

def main(argv):
    ap = argparse.ArgumentParser(prog='setup', add_help=True)
    ap.add_argument('--data')
    ap.add_argument('--plugin-root')
    ap.add_argument('--yes', action='store_true')
    ap.add_argument('--keys', default='')
    ap.add_argument('--name', help='with --skeleton: the business name for a new manifest.yaml')
    ap.add_argument('--open', metavar='DIR', help='with --suggest: the folder the conversation is open on (default: the working folder)')
    ap.add_argument('--offer-drive-icloud', action='store_true', help='with --suggest: also suggest Google Drive or iCloud Drive (untested)')
    g = ap.add_mutually_exclusive_group()
    g.add_argument('--choose', metavar='DIR')
    g.add_argument('--suggest', metavar='NAME', nargs='?', const='')
    g.add_argument('--inspect', metavar='DIR')
    for m in ('check', 'skeleton-only', 'skeleton', 'grant', 'codex-status', 'codex-block', 'explain-memory', 'remove'):
        g.add_argument('--' + m, action='store_true')
    g.add_argument('--set-name', metavar='NAME', help='write the business name into a manifest.yaml that still says My Business')
    g.add_argument('--key-store', metavar='NAME')
    g.add_argument('--key-check', metavar='NAME')
    a = ap.parse_args(argv)
    root = plugin_root(a.plugin_root)
    data, source = data_folder(a.data)

    if a.explain_memory:
        say(MEMORY_NOTE)
        return 0
    if a.suggest is not None:
        if a.open is not None:
            open_dir = a.open
        else:
            try:
                open_dir = os.getcwd()
            except OSError:
                open_dir = ''
        return suggest(a.suggest, open_dir, a.offer_drive_icloud)
    if a.inspect is not None:
        return inspect(a.inspect)
    if a.key_store:
        return key_store(a.key_store)
    if a.key_check:
        return key_check(a.key_check)
    if a.codex_status:
        say(json.dumps(codex_status(), indent=2))
        return 0
    if a.remove:
        return remove(data, a.yes, [k for k in a.keys.split(',') if k])
    if a.choose is not None:
        return choose(root, a.choose, a.data, a.yes)
    if data is None and not a.check:
        say('setup: no business folder is chosen yet. Run setup\'s folder step first (--choose, for example --choose "~/%s"). Nothing was written.' % FALLBACK_NAME)
        return 2
    if a.set_name is not None:
        return set_name(data, a.set_name)
    if a.grant:
        return grant(data, a.yes)
    if a.codex_block:
        return codex_block(data, a.yes)
    if a.skeleton or a.skeleton_only:
        if root is None:
            say('setup: cannot find the plugin folder from %s. Nothing was written.' % __file__)
            return 2
        created, kept = copy_skeleton(root, data, (a.name or '').strip() or None)
        return report(root, data, source, created, kept)
    return report(root, data, source)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
