#!/usr/bin/env bash
# Merlin SessionStart hook (Claude Code and Codex).
#
# Prints one JSON line whose additionalContext is a short status header plus the
# rules digest (rules/digest.md). It also keeps the pointer file
# ~/.merlin/instance.json in step with the plugin option "Your Merlin data folder":
#
#   - option set, folder exists and is writable: write the pointer when it is
#     missing or names a different folder; leave it byte for byte when it matches.
#   - folder missing, not a folder, or not writable: leave the pointer alone and
#     report read-only with the reason.
#   - option unset (Codex has no plugin options): never write; use the folder the
#     pointer already names, if any.
#
# Only the hook may read plugin variables; skills and their scripts never get them.
# Honours a HOME override. Needs bash only: no python3, no node.

set -u

ROOT="${CLAUDE_PLUGIN_ROOT:-${PLUGIN_ROOT:-}}"
if [ -z "$ROOT" ]; then
  ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi
OPTION="${CLAUDE_PLUGIN_OPTION_DATA_DIR:-}"
POINTER_DIR="${HOME}/.merlin"
POINTER="${POINTER_DIR}/instance.json"
BUILD_MARKER='<!-- Generated by the plugin build.'

# Read and ignore the event JSON, so the caller never blocks on a full pipe.
if [ ! -t 0 ]; then cat >/dev/null 2>&1 || true; fi

json_escape() {
  local s=$1
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//$'\n'/\\n}
  s=${s//$'\r'/\\r}
  s=${s//$'\t'/\\t}
  printf '%s' "$s"
}

json_unescape() {
  local s=$1
  s=${s//\\\"/\"}
  s=${s//\\\\/\\}
  printf '%s' "$s"
}

expand_home() {
  case "$1" in
    "~") printf '%s' "$HOME" ;;
    "~/"*) printf '%s/%s' "$HOME" "${1#\~/}" ;;
    *) printf '%s' "$1" ;;
  esac
}

pointer_value() { # $1 key: prints the string value from the pointer, or nothing
  [ -f "$POINTER" ] || return 0
  local line
  line=$(grep -m1 "^[[:space:]]*\"$1\":" "$POINTER" 2>/dev/null) || return 0
  line=${line#*\": \"}
  line=${line%\"*}
  json_unescape "$line"
}

VERSION=$(sed -n 's/^[[:space:]]*"version":[[:space:]]*"\([^"]*\)".*/\1/p' "$ROOT/.claude-plugin/plugin.json" 2>/dev/null | head -n1)
[ -n "$VERSION" ] || VERSION="unknown"

DATA=""
SOURCE=""
if [ -n "$OPTION" ]; then
  DATA=$(expand_home "$OPTION")
  SOURCE="option"
else
  DATA=$(pointer_value data_root)
  [ -n "$DATA" ] && SOURCE="pointer"
fi

STATE=""
REASON=""
POINTER_NOTE=""
if [ -z "$DATA" ]; then
  STATE="unset"
elif [ "${DATA#/}" = "$DATA" ]; then
  STATE="readonly"; REASON="the folder setting is not a full path (it should start with /)"
elif [ ! -e "$DATA" ]; then
  STATE="readonly"; REASON="the folder does not exist (moved, renamed, or a drive that is not connected)"
elif [ ! -d "$DATA" ]; then
  STATE="readonly"; REASON="that path is a file, not a folder"
elif [ ! -w "$DATA" ] || [ ! -x "$DATA" ]; then
  STATE="readonly"; REASON="this computer account cannot write to that folder"
else
  CANON=$(cd "$DATA" 2>/dev/null && pwd -P)
  [ -n "$CANON" ] && DATA="$CANON"
  if [ -f "$DATA/manifest.yaml" ]; then STATE="ready"; else STATE="notsetup"; fi
fi

# Pointer: written only from the plugin option, only for a reachable folder.
if [ "$SOURCE" = "option" ] && { [ "$STATE" = "ready" ] || [ "$STATE" = "notsetup" ]; }; then
  CURRENT=$(pointer_value data_root)
  if [ -f "$POINTER" ] && [ "$CURRENT" = "$DATA" ]; then
    POINTER_NOTE="The pointer file ~/.merlin/instance.json already names this folder."
  else
    if mkdir -p "$POINTER_DIR" 2>/dev/null; then
      TMP="${POINTER_DIR}/.instance.json.$$"
      D=$(json_escape "$DATA")
      NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
      if printf '{\n  "data_root": "%s",\n  "praxis_root": "%s",\n  "written_by": "merlin plugin %s, session-start hook",\n  "written_at": "%s",\n  "data_access": "local"\n}\n' \
          "$D" "$D" "$VERSION" "$NOW" > "$TMP" 2>/dev/null && mv -f "$TMP" "$POINTER" 2>/dev/null; then
        POINTER_NOTE="The pointer file ~/.merlin/instance.json was written now and names this folder."
      else
        rm -f "$TMP" 2>/dev/null
        POINTER_NOTE="The pointer file ~/.merlin/instance.json could not be written. Scripts and Codex will not find this folder until it can be."
      fi
    else
      POINTER_NOTE="The folder ~/.merlin could not be created, so the pointer file was not written. Scripts and Codex will not find the data folder until it can be."
    fi
  fi
elif [ "$SOURCE" = "pointer" ]; then
  POINTER_NOTE="This folder comes from the pointer file ~/.merlin/instance.json, which Claude Code keeps up to date."
elif [ "$STATE" = "readonly" ]; then
  POINTER_NOTE="The pointer file ~/.merlin/instance.json was left as it was."
fi

case "$STATE" in
  ready)
    STATUS="Status: ready. Merlin data folder: ${DATA}. Setup has run. ${POINTER_NOTE}" ;;
  notsetup)
    STATUS="Status: setup has not run. Merlin data folder: ${DATA}. The folder exists but has no manifest.yaml yet. Before other Merlin work, tell the user once, in plain words, to run merlin:setup. ${POINTER_NOTE}" ;;
  readonly)
    STATUS="Status: read-only. Merlin data folder: ${DATA}. Reason: ${REASON}. Merlin only reads this session and writes nothing anywhere until the folder is back. Tell the user which folder and what is wrong with it. ${POINTER_NOTE}" ;;
  *)
    STATUS="Status: read-only. No Merlin data folder is chosen yet, so Merlin writes nothing this session. Tell the user to set the plugin option \"Your Merlin data folder\" (in Claude Code: the /plugin screen, or claude plugin configure in a terminal), then start a new session. In Codex, open Claude Code once first: it records the folder for Codex." ;;
esac

DIGEST=""
if [ -f "$ROOT/rules/digest.md" ]; then
  DIGEST=$(grep -v -F "$BUILD_MARKER" "$ROOT/rules/digest.md")
else
  DIGEST="The Merlin rules digest is missing from the plugin folder (${ROOT}/rules/digest.md). Your Merlin data folder wins over any Claude memory. Run merlin:rules for the full rules."
fi

TEXT="# Merlin ${VERSION}
${STATUS}

${DIGEST}"

printf '{"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": "%s"}}\n' "$(json_escape "$TEXT")"
exit 0
