#!/usr/bin/env bash
# Merlin SessionStart hook (Claude Code and Codex).
#
# Prints one JSON line whose additionalContext is a short status header plus the
# rules digest (rules/digest.md). The Merlin data folder comes from the plugin
# option "Your Merlin data folder" when it is set, otherwise from the pointer file
# ~/.merlin/instance.json, which merlin:setup writes when the user chooses a folder
# in chat. A desktop-app install often cannot set the option at all, so the
# pointer is the normal source there.
#
#   - option set, folder exists and is writable: write the pointer when it is
#     missing or names a different folder; leave it byte for byte when it matches.
#   - folder missing, not a folder, or not writable: leave the pointer alone and
#     report read-only with the reason.
#   - option unset: never write; use the folder the pointer names, if any. With
#     no pointer either, no folder is chosen yet: that is not read-only, and the
#     status tells the user to run /merlin:setup.
#
# Only the hook may read plugin variables; skills and their scripts never get them.
# Honours a HOME override. Needs bash only: no python3, no node.

set -u

ROOT="${CLAUDE_PLUGIN_ROOT:-${PLUGIN_ROOT:-}}"
if [ -z "$ROOT" ]; then
  ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi
OPTION="${CLAUDE_PLUGIN_OPTION_DATA_DIR:-}"
POINTER_DIR="${HOME}/.merlin"
POINTER="${POINTER_DIR}/instance.json"
BUILD_MARKER='<!-- Generated by the plugin build.'

# Read and ignore the event JSON, so the caller never blocks on a full pipe.
if [ ! -t 0 ]; then cat >/dev/null 2>&1 || true; fi

json_escape() {
  local s=$1
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//$'\n'/\\n}
  s=${s//$'\r'/\\r}
  s=${s//$'\t'/\\t}
  printf '%s' "$s"
}

json_unescape() {
  local s=$1
  s=${s//\\\"/\"}
  s=${s//\\\//\/}
  s=${s//\\\\/\\}
  printf '%s' "$s"
}

expand_home() {
  case "$1" in
    "~") printf '%s' "$HOME" ;;
    "~/"*) printf '%s/%s' "$HOME" "${1#\~/}" ;;
    *) printf '%s' "$1" ;;
  esac
}

pointer_value() { # $1 key: prints the string value from the pointer, or nothing
  # Reads pretty-printed and one-line JSON alike: a hand-written or compact pointer
  # must never read as "no folder".
  [ -f "$POINTER" ] || return 0
  local raw val
  raw=$(tr '\n\r' '  ' < "$POINTER" 2>/dev/null) || return 0
  val=$(printf '%s' "$raw" | sed -nE 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"(([^"\\]|\\.)*)".*/\1/p')
  case "$val" in
    *'\u'*)
      # A \uXXXX escape (another tool's JSON writer): decode it with python3 when it is
      # there; without python3 the value is used as written.
      if command -v python3 >/dev/null 2>&1; then
        local dec
        if dec=$(python3 -c 'import json,sys; sys.stdout.write(json.loads("\"" + sys.argv[1] + "\""))' "$val" 2>/dev/null); then
          printf '%s' "$dec"; return 0
        fi
      fi ;;
  esac
  json_unescape "$val"
}

VERSION=$(sed -n 's/^[[:space:]]*"version":[[:space:]]*"\([^"]*\)".*/\1/p' "$ROOT/.claude-plugin/plugin.json" 2>/dev/null | head -n1)
[ -n "$VERSION" ] || VERSION="unknown"

DATA=""
SOURCE=""
if [ -n "$OPTION" ]; then
  DATA=$(expand_home "$OPTION")
  SOURCE="option"
else
  DATA=$(pointer_value data_root)
  [ -n "$DATA" ] && SOURCE="pointer"
fi

STATE=""
REASON=""
POINTER_NOTE=""
if [ -z "$DATA" ]; then
  STATE="unset"
elif [ "${DATA#/}" = "$DATA" ]; then
  STATE="readonly"; REASON="the folder setting is not a full path (it should start with /)"
elif [ ! -e "$DATA" ]; then
  STATE="readonly"; REASON="the folder does not exist (moved, renamed, or a drive that is not connected)"
elif [ ! -d "$DATA" ]; then
  STATE="readonly"; REASON="that path is a file, not a folder"
elif [ ! -w "$DATA" ] || [ ! -x "$DATA" ]; then
  STATE="readonly"; REASON="this computer account cannot write to that folder"
else
  CANON=$(cd "$DATA" 2>/dev/null && pwd -P)
  [ -n "$CANON" ] && DATA="$CANON"
  if [ -f "$DATA/manifest.yaml" ]; then STATE="ready"; else STATE="notsetup"; fi
fi

# Pointer: written only from the plugin option, only for a reachable folder.
if [ "$SOURCE" = "option" ] && { [ "$STATE" = "ready" ] || [ "$STATE" = "notsetup" ]; }; then
  CURRENT=$(pointer_value data_root)
  if [ -f "$POINTER" ] && [ "$CURRENT" = "$DATA" ]; then
    POINTER_NOTE="The pointer file ~/.merlin/instance.json already names this folder."
  else
    if mkdir -p "$POINTER_DIR" 2>/dev/null; then
      TMP="${POINTER_DIR}/.instance.json.$$"
      D=$(json_escape "$DATA")
      NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
      if printf '{\n  "data_root": "%s",\n  "praxis_root": "%s",\n  "written_by": "merlin plugin %s, session-start hook",\n  "written_at": "%s",\n  "data_access": "local"\n}\n' \
          "$D" "$D" "$VERSION" "$NOW" > "$TMP" 2>/dev/null && mv -f "$TMP" "$POINTER" 2>/dev/null; then
        POINTER_NOTE="The pointer file ~/.merlin/instance.json was written now and names this folder."
      else
        rm -f "$TMP" 2>/dev/null
        POINTER_NOTE="The pointer file ~/.merlin/instance.json could not be written. Scripts and Codex will not find this folder until it can be."
      fi
    else
      POINTER_NOTE="The folder ~/.merlin could not be created, so the pointer file was not written. Scripts and Codex will not find the data folder until it can be."
    fi
  fi
elif [ "$SOURCE" = "pointer" ]; then
  POINTER_NOTE="This folder comes from the pointer file ~/.merlin/instance.json."
  if [ "$STATE" = "readonly" ]; then
    POINTER_NOTE="${POINTER_NOTE} If the folder was moved or renamed on purpose, merlin:setup can record the new one after the user's yes."
  fi
elif [ "$STATE" = "readonly" ]; then
  POINTER_NOTE="The pointer file ~/.merlin/instance.json was left as it was."
fi

case "$STATE" in
  ready)
    STATUS="Status: ready. Merlin data folder: ${DATA}. Setup has run. ${POINTER_NOTE}" ;;
  notsetup)
    STATUS="Status: setup has not run. Merlin data folder: ${DATA}. The folder exists but has no manifest.yaml yet. Before other Merlin work, tell the user once, in plain words, to run merlin:setup. ${POINTER_NOTE}" ;;
  readonly)
    STATUS="Status: read-only. Merlin data folder: ${DATA}. Reason: ${REASON}. Merlin only reads this session and writes nothing anywhere until the folder is back. Tell the user which folder and what is wrong with it. ${POINTER_NOTE}" ;;
  *)
    STATUS="Status: no Merlin data folder chosen yet. This is not read-only. Before other Merlin work, tell the user once, in plain words, to run /merlin:setup: it asks which folder to use and records it after their yes. Until a folder is chosen, Merlin writes nothing except what merlin:setup writes after the user's yes. A folder merlin:setup records counts from then on, in this session too, with no new session needed. In Codex, merlin:setup records the folder the same way." ;;
esac

DIGEST=""
if [ -f "$ROOT/rules/digest.md" ]; then
  DIGEST=$(grep -v -F "$BUILD_MARKER" "$ROOT/rules/digest.md")
else
  DIGEST="The Merlin rules digest is missing from the plugin folder (${ROOT}/rules/digest.md). Your Merlin data folder wins over any Claude memory. Run merlin:rules for the full rules."
fi

TEXT="# Merlin ${VERSION}
${STATUS}

${DIGEST}"

printf '{"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": "%s"}}\n' "$(json_escape "$TEXT")"
exit 0
